name: Update vless reality

on:
  schedule:
    - cron: '0 */6 * * *'  # هر 6 ساعت یکبار
  workflow_dispatch:  # اجرای دستی

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # مجوز نوشتن در مخزن
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # استفاده از توکن پیش‌فرض گیت‌هاب
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Run filter script
      run: |
        python filter_reality.py
    
    - name: Commit and push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add vless_reality.txt
        git diff --staged --quiet || (git commit -m "Auto-update shadowsocks configs (port 443) - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
